---
- hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  gather_facts: true #coleta de informações dos hosts, informações por exemplo de discos, sistema operacional, informações de endereço ip e etc...
  tasks:
    - name: 'Instalação de pacotes webserver'
      become: yes
      apt:
        pkg:
          - php7.4
          - php-pear
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-xmlrpc
          - php7.4-mysql
          - apache2
          - python3-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian' #só vai instalar os pacotes onde OS for distribuição Debian
    - name: 'Diretório do webserver'
      file:
        path: /srv/www
        state: directory
        owner: "{{app_user}}"
        mode: "0775"
    - name: 'Download e Extração do arquivo de aplicação'
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
    - name: 'Substitui IP de Conexão com o Banco de Dados'
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.102'

